#!/bin/sh
REPO_ROOT=$(git rev-parse --show-toplevel)

die() {
    echo "$1";
    exit 1;
}

update_colophon() {
    COLOPHON_PATH=$(python tools/colophon.py) || die 'The colophon file could not be generated.'
    COLOPHON_PATH=${COLOPHON_PATH//\\//}
    COLOPHON_PATH=${COLOPHON_PATH#"$REPO_ROOT"/}
}

if [ -f .venv/Scripts/activate ]; then
    . .venv/Scripts/activate
else
    . .venv/bin/activate
fi