#!/bin/sh
#
# Check that documentation is up-to-date and corresponds to the current
# code that is going to be committed (if any).

SELF_DOCUMENTING_CODE="src/legion/__init__.py"
GENERATED_DOCUMENTATION="README.md"

if ! git diff --cached --name-only | grep -q "^$SELF_DOCUMENTING_CODE$"
then
    exit 0
fi

.venv/Scripts/python.exe -m legion

if ! git diff --quiet $GENERATED_DOCUMENTATION
then
  echo "$GENERATED_DOCUMENTATION is out of date."
  exit 1
fi

exit 0