#!/bin/sh
. "$(dirname "$0")/common"

SELF_DOCUMENTING_CODE='src/legion/__init__.py'
GENERATED_DOCUMENTATION='README.md'

update_about
git add '**/about.py'

git diff --cached --name-only | grep -q "^$SELF_DOCUMENTING_CODE$" || exit 0

python -m legion || die "Failed to generate $GENERATED_DOCUMENTATION."

git diff --quiet $GENERATED_DOCUMENTATION || die "$GENERATED_DOCUMENTATION is out of date."