"""Generate project metadata and dump it to `about.py`."""  # noqa: INP001
import contextlib
from pathlib import Path
import sys
from textwrap import dedent

from legion import excepthook, git_repository_root, load_pyproject, resolve_version

STATUS_SUCCESS = 0
STATUS_FAILURE = 1
def main() -> int:
    """."""
    sys.excepthook = excepthook

    if (project_root := git_repository_root()) is None:
        return STATUS_FAILURE

    if (package_metadata := load_pyproject(project_root)) is None:
        return STATUS_FAILURE

    if (version := resolve_version()) is None:
        return STATUS_FAILURE

    name = package_metadata['project']['name']
    about_contents = dedent(f'''
        """Auto generated by `{Path(__file__).name}` for package `{name}` - do not edit."""

        # pylint: disable=unused-variable
        PROGRAM_NAME = '{name}'
        VERSION = '{version}'
        REPOSITORY = '{package_metadata['project']['urls']['source']}'
    ''').lstrip()

    about_path = project_root / 'src' / name / 'about.py'
    with contextlib.suppress(PermissionError, FileNotFoundError):
        about_path.write_text(about_contents, encoding='utf-8')
        return STATUS_SUCCESS

    return STATUS_FAILURE


if __name__ == '__main__':
    sys.exit(main())
